services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app
      - n8n
    networks:
      - net

  app:
    image: node:alpine
    working_dir: /app
    volumes:
      - ./app:/app
    command: ["node", "app.js"]
    restart: unless-stopped
    networks:
      - net

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    volumes:
      - n8n:/home/node/.n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
    restart: unless-stopped
    networks:
      - net

networks:
  net:

volumes:
  n8n:
